config/docker-registry/charts/docker-registry/templates/deployment.yaml
config/docker-registry/values.yaml
sec-scanners-config.yaml

- use `external/registry` instead of `tpi/registry` image
- define usage of the `registry-init` image
- https://github.com/kyma-project/docker-registry/issues/18

Use the `registry` image synced by the image-syncer

---

.github/workflows/operator-verify.yaml
components/operator/Makefile

Turn off temporary update-integration GA job because of absence of release.
Gardener-integration is working now - the configuration is set correctly.

Turn off update-integration GA job because of absence of release

---

.github/scripts/upgrade-sec-scanners-config.sh

- fix values paths in release scripts
#27

Fix values paths after chart refactor

---

hack/gardener.mk
hack/save_kubeconfig.sh
hack/shoot_template.yaml

- Deprecate `kyma provision gardener`
- https://github.com/kyma-project/kyma/issues/18674

Deprecate kyma provision gardener

---

components/operator/api/v1alpha1/dockerregistry_types.go
components/operator/internal/chart/flags.go
components/operator/internal/chart/flags_test.go
components/operator/internal/state/controller_configuration.go
components/operator/internal/state/controller_configuration_test.go
tests/operator/main.go

- remote the `HealthzLivenessTimeout` type from the DockerRegistry CR because it's not used anywhere
- https://github.com/kyma-project/docker-registry/issues/37#issue-2297243298

Remove unused fields from the CR's types

---

components/operator/internal/state/initialize.go
components/operator/internal/state/initialize_test.go
components/operator/internal/state/registry.go
components/operator/internal/state/registry_test.go
components/operator/internal/state/storage.go
components/operator/internal/state/storage_test.go
config/operator/base/crd/bases/operator.kyma-project.io_dockerregistries.yaml

- split the registry state function into storage and access config to make this state functions more single responsibility and open for further refactors and feature requests

Split the `sFnRegistryConfiguration` function

---

docs/user/resources/06-20-docker-registry-cr.md
docs/user/technical-reference/04-30-storage-configuration.md

- document storage field in the DockerRegistry CR
- add a technical reference with a description of how configure storage
- https://github.com/kyma-project/docker-registry/issues/25#issue-2287513647

Document registry storage

---

components/operator/internal/registry/secret.go
components/operator/internal/state/registry_test.go
config/docker-registry/templates/registry-config.yaml

- the `inInternal` field was used by the Serverless nad DockerRegistry is not a part of serverless any longer

Remove `isInternal` field

---

components/operator/internal/state/access.go
components/operator/internal/state/access_test.go
components/operator/internal/state/utils.go

- cover case when a user set the `.spec.externalAccess.hostPrefix` field

Implement the `HostPrefix` for external access

---

.github/workflows/build-push-release.yaml

- fix job and variable names in gh workflow build
- rename gh workflow build-push to build-push-release
See also #83

fix job and variable names in gh workflow build

---

components/operator/internal/istio/istio.go
components/operator/internal/registry/external_access.go
components/operator/internal/registry/external_access_test.go
components/operator/internal/state/access.go
components/operator/internal/state/access_test.go

- set warning if custom gateway is not available
- fix warning message
- https://github.com/kyma-project/docker-registry/issues/106#issue-2424710286

Warn user when custom gateway is not available

---

.github/workflows/_integration-tests.yaml

- use `sha` instead of `run_id`
#127

Use github SHA intead of run_id as a part of btp integration test name

---

config/operator/base/ui-extensions/dockerregistry/form

Display storage type under the `storage` formGroup widget

---

tests/btp/hack/registry-availibility-check.sh

- rework avail. check as it [fails](https://github.com/kyma-project/docker-registry/actions/runs/11741523966/job/32724522077#step:6:97). In [ci-demo](https://github.tools.sap/kyma/ci-automation-demo/blob/main/ci/registry-availibility-check.sh) it works

Fix retrying for req avail checks

---

.github/scripts/verify-actions-status.sh

- gardener tests are gone. No need to check them upon release. Check all `push` CI workflows instead

Properly check main status before release

---

.github/actions/setup-kyma/action.yaml

- Tests workflow will use always the latest stable release

Use latest stable CLI in integration tests

---

.github/actions/setup-kyma/action.yaml

- cherry-pick https://github.com/kyma-project/docker-registry/pull/323

Cherry-pick: Use latest stable CLI in integration tests (#323)

---

config/docker-registry/files/kyma-commands.yaml

- migrate from the `configPath` inside the `flags` and `args` into go templates in the `with` config
- https://github.com/kyma-project/cli/issues/2428

Stop using configPath in cli extension

---

.github/scripts/upgrade-sec-scanners-config.sh
.github/workflows/_images-verify.yaml

- fix all repo scripts working on the `sec-scannr-config` to use  the `bdba` instead of the `protecode` field
- https://github.com/kyma-project/keda-manager/issues/617

Fix scripts using the `sec-scanner-config` file

---

docs/user/tutorials/01-10-use-registry-internally.md
docs/user/tutorials/01-30-remove-image-manifest.md
tests/btp/Makefile

This reverts commit f470c1a2ea2f66b64b5f344d2581bb50148c7f5a.
- revert commit to support old CLI (new one is not released yet)
- https://github.com/kyma-project/docker-registry/issues/369

Revert "Migrate the `kyma registry` extension (#346)"

---

hack/k3d.mk

- use k3d CLI to provision k3d instead of deprecated v2 `kyma provision k3d` command
https://github.com/kyma-project/cli/issues/2051

Remove dependency to Kyma CLI v2
