.github/actions/rebase/action.yaml
.github/workflows/markdown.yaml
.github/workflows/operator-verify.yaml

- propose the `rebase` action
- implement new action in all `pre` jobs
- https://github.com/kyma-project/serverless/issues/971

Create the `rebase` action

---

components/operator/Makefile

Fix path to `dockerregistry-operator.yaml` from release

Fix path to dockerregistry-operator.yaml from release

---

.github/workflows/upgrade-tests.yaml

enable upgrade-tests

---

hack/shoot_template.yaml

- Don't hibernate Gardener cluster, as it is removed after the test
- https://github.com/kyma-project/kyma/issues/18674

Don't hibernate Gardener cluster

---

.github/workflows/markdown.yaml

Remove running markdown link checker on schedule

remove markdown link checker on schedule

---

docs/user/tutorials/01-20-expose-registry.md

- add on md with tutorial how to expose Registry with Istio

Document how to expose Registry with Istio

---

components/operator/internal/state/configuration_status.go
components/operator/internal/state/configuration_status_test.go
components/operator/internal/state/registry.go
components/operator/internal/state/registry_test.go

- rename the `sFnControllerConfiguration` to the `sFnConfigurationStatus` - this name better describes functions responsibility
- add one TODO that describes where the func should be located in the reconciliation chain 

Refactor the `sFnControllerConfiguration` state function

---

components/operator/internal/state/configuration_status.go

- add s3 status field
- #25
/cc @pPrecel

add s3 status field

---

config/operator/base/crd/kustomization.yaml
config/operator/base/deployment/deployment.yaml
config/operator/base/kustomization.yaml
config/operator/base/rbac/editor_role.yaml
config/operator/base/rbac/kustomization.yaml
config/operator/base/rbac/role_binding.yaml
config/operator/base/rbac/service_account.yaml
config/operator/base/rbac/viewer_role.yaml
config/operator/base/ui-extensions/dockerregistry/kustomization.yaml

- Consistent labeling
- https://github.com/kyma-project/serverless/issues/1014

Use consistent labels

---

config/operator/base/crd/bases/operator.kyma-project.io_dockerregistries.yaml
config/operator/base/crd/kustomization.yaml
config/operator/base/deployment/deployment.yaml
config/operator/base/kustomization.yaml

- label selectors are immutable, they cannot be changed without deleting deployment completely
- https://github.com/kyma-project/serverless/issues/1014

restore old label selector

---

components/operator/internal/chart/flags.go
components/operator/internal/state/storage.go

- Cleanup pvc when s3 or azure is used
- #64

Cleanup pvc when s3 or azure is used

---

components/operator/internal/state/configuration_status.go
components/operator/internal/state/configuration_status_test.go

Update status when registry is exposed

---

components/operator/internal/state/storage_test.go

Fix storage tests

---

components/operator/internal/registry/external_access.go
components/operator/internal/registry/external_access_test.go
components/operator/internal/state/access.go
components/operator/internal/state/access_test.go
components/operator/internal/state/configuration_status.go
components/operator/internal/state/configuration_status_test.go

Warn user when gateway can't be used

---

components/operator/api/v1alpha1/dockerregistry_types.go
components/operator/controllers/controller_test.go
components/operator/internal/registry/secret.go
components/operator/internal/state/access_test.go
components/operator/internal/state/configuration_status.go
components/operator/internal/state/configuration_status_test.go
components/operator/main.go
config/operator/base/crd/bases/operator.kyma-project.io_dockerregistries.yaml

- move the `PullAddress` to the NetworkAccess struct
- add the `Enabled` field to the `NetworkAccess` struct
- https://github.com/kyma-project/docker-registry/issues/37#issue-2297243298

refactor status types

---

components/operator/internal/controllers/kubernetes/namespace_controller.go
components/operator/internal/controllers/kubernetes/secret_service.go
components/operator/internal/controllers/kubernetes/shared.go
components/operator/main.go

- add external secret propagation
See also #37

add external secret propagation

---

docs/user/00-30-storage-configuration.md
docs/user/technical-reference/resources/06-20-docker-registry-cr.md

Add btp storage docs

---

components/operator/Dockerfile
components/registry-init/Dockerfile

- enable possibility to build registry images
- https://github.com/kyma-project/serverless/issues/942

Use synced images in Dockerfiles

---

.github/workflows/promote-to-release-channel.yaml
Makefile

- Add promote to release channel action
- Add `module-config` make target
#91

Add promote to release channel action

---

docs/user/00-30-storage-configuration.md

- Fix link to `docker-registry-cr.md`

Fix link to docker-registry-cr.md

---

docs/user/00-30-storage-configuration.md

- Fix second link to `docker-registry-cr.md`

Fix second link to docker-registry-cr.md

---

components/operator/internal/state/storage.go
components/operator/internal/state/storage_test.go
docs/user/00-30-storage-configuration.md

- Disable Azure support for BTP
- #66
- https://github.com/distribution/distribution/issues/4405

Disable Azure support for BTP

---

.github/workflows/build-push.yaml
.github/workflows/build-release.yaml

Fix release

---

.github/workflows/build-release.yaml

Fix regular expression

---

.github/workflows/build-release.yaml

Fix build (release) name

---

.github/workflows/create-release.yaml

- Change `permissions: contents` to `write` instead of only `read`
#112

Allow pushing tag to repo

---

.github/workflows/create-release.yaml

- Add needs for publish release

Add needs for publish release

---

.github/workflows/_build-pull.yaml
.github/workflows/_build-push.yaml
.github/workflows/_images-verify.yaml
.github/workflows/_integration-tests-pull.yaml
.github/workflows/_integration-tests-push.yaml
.github/workflows/_unit-tests.yaml
.github/workflows/_upgrade-tests.yaml
.github/workflows/pull.yaml
.github/workflows/push.yaml

- create main gh workflows for pull and push events
See also #98

create main gh workflows for pull and push events

---

.github/workflows/_build-pull.yaml
.github/workflows/_build-push.yaml
.github/workflows/_images-verify.yaml
.github/workflows/_integration-tests-pull.yaml
.github/workflows/_integration-tests-push.yaml
.github/workflows/_unit-tests.yaml
.github/workflows/_upgrade-tests.yaml
.github/workflows/pull.yaml
.github/workflows/push.yaml

-disable workflows on pull_request/push
- https://github.com/kyma-project/docker-registry/issues/98

Run workflows once

---

.github/workflows/_integration-tests.yaml
.github/workflows/create-release.yaml
.github/workflows/pull.yaml
.github/workflows/push.yaml

- https://github.com/kyma-project/docker-registry/issues/98

Reuse integrations in the release flow

---

sec-scanners-config.yaml

Bump rc tag to 0.1.0

---

.github/workflows/_build.yaml
.github/workflows/_integration-tests.yaml

- from time to time we run workflows from the `pull_request` or the `pull_request_target` events
- https://github.com/kyma-project/docker-registry/issues/98

Fix pull detection

---

docs/contributor/04-10-testing-strategy.md

- https://github.com/kyma-project/docker-registry/issues/98

Update testing strategy

---

.github/workflows/create-release.yaml
.github/workflows/pull.yaml
.github/workflows/push.yaml

- add the `secrets: inherit` to right jobs
- https://github.com/kyma-project/serverless/issues/1089
- https://github.com/kyma-project/serverless/issues/1090

Pass secrets to called integration and upgrade workflows

---

.github/workflows/_integration-tests.yaml
hack/save_kubeconfig.sh

- cherry-pick:
- https://github.com/kyma-project/serverless/pull/1104
- https://github.com/kyma-project/serverless/pull/1105
- https://github.com/kyma-project/serverless/pull/1106
- https://github.com/kyma-project/serverless/issues/1089
- https://github.com/kyma-project/serverless/issues/1090

Cherry-pick last serverless changes in context of integration tests readability

---

.github/workflows/promote-to-release-channel.yaml
module-config-template.yaml

- Adjust name in `module-config-template` 
- Change dir in `promote-to-release-channel` to `docker-registry`

Fix module-config & change dir to docker-registry

---

.github/workflows/create-release.yaml

- Fix build (release) workflow call

Fix build (release) workflow call

---

hack/save_kubeconfig.sh

- add the `set -eo pipefail` at the beginning of the provisioning script
- https://github.com/kyma-project/serverless/issues/1089
- https://github.com/kyma-project/serverless/issues/1090

Fail workflow when provisioning is not succeed

---

.github/dependabot.yml

- Add missing images to dependabot

Add missing images to dependabot

---

config/docker-registry/values.yaml

- Bump registry image to one that have up to 100% less vulnerabilities

Bump registry image

---

sec-scanners-config.yaml

- Bump registry image in sec-config

Bump registry image in sec-config

---

components/operator/api/v1alpha1/dockerregistry_types.go
components/operator/internal/state/installed_status.go
components/operator/internal/state/installed_status_test.go
config/operator/base/crd/bases/operator.kyma-project.io_dockerregistries.yaml

- Add pvc name to status
- #51

Add pvc name to status

---

.github/workflows/lint.yaml

Turn on lint job on all PRs

---

docs/user/tutorials/01-20-expose-registry.md

- use info from docker registry CR status to push images and schedule workloads using internal pull address
- ...
- ...
https://github.com/kyma-project/docker-registry/issues/37

improve docs about exposure

---

docs/user/00-30-storage-configuration.md
docs/user/technical-reference/resources/06-20-docker-registry-cr.md

Add PVC docs

---

config/operator/base/ui-extensions/dockerregistry/details
config/operator/base/ui-extensions/dockerregistry/form
config/operator/base/ui-extensions/dockerregistry/general
config/operator/base/ui-extensions/dockerregistry/kustomization.yaml
config/operator/base/ui-extensions/dockerregistry/list
config/operator/base/ui-extensions/dockerregistry/translations

Add busola extension

---

tests/btp/hack/Makefile

- Fix kubectl apply from `-k` to `-f`
#127

Fix kubectl apply -f

---

.github/workflows/_integration-tests.yaml

- Remove `tf destroy` from `btp integration test`
#127

Rm tf destroy from btp integration test

---

.github/workflows/create-release.yaml
config/operator/base/kustomization.yaml
hack/replace_docker_registry_version.sh

Added a script to bump version and used it in release pipeline
https://github.com/kyma-project/keda-manager/issues/453

Automate Docker Registry image bumping during release 

---

components/operator/.golangci.yaml
components/operator/internal/state/fsm.go
components/operator/internal/state/installed_status.go

- Unify linter config
- https://github.com/kyma-project/serverless/issues/1038

Unify linter config

---

components/operator/.golangci.yaml
components/operator/internal/state/fsm.go
components/operator/internal/state/installed_status.go

This reverts commit 731a476af0d5748c42538bfb0555727f8bbf88aa.
- ...
- ...
- ...

Revert "Unify linter config (#174)"

---

components/operator/.golangci.yaml
components/operator/internal/state/installed_status.go

- Lint tests
- https://github.com/kyma-project/serverless/issues/1038

Lint tests

---

config/operator/base/kustomization.yaml
hack/replace_docker_registry_version.sh

- Fix release version upgrade - `commonLabels` also affects label selectors,w hich are immutable, making upgrade impossible
- https://github.com/kyma-project/keda-manager/issues/453

Fix release version upgrade

---

sec-scanners-config.yaml

bump rc tag

---

components/operator/Dockerfile

Bump base golang image

---

config/operator/base/crd/kustomization.yaml
config/operator/base/kustomization.yaml

- Fix labels in deployment template

Fix labels

---

hack/tools.mk

Fix controller-gen target to correctly detect version

---

.github/workflows/_images-verify.yaml
.github/workflows/pull.yaml

Run image-verify workflow on PRs to main only v2

---

tests/btp/tf/main.tf

Bump tf http provider

---

README.md

Fix link in root Docker Registry repo

---

components/operator/internal/state/storage.go
components/operator/internal/state/storage_test.go

- check if specified PVC exists and return error if not
- https://github.com/kyma-project/docker-registry/issues/140

Error when the PVC can't be reached

---

README.md
docs/user/00-30-storage-configuration.md

Fix broken links in Docker Registry

---

go.mod
go.sum

Bump grpc dependency

---

tests/btp/tf/main.tf

- bump sap btp tf provider
- use fixed kyma module

Bump sap/btp provider to 1.7.0 and use fixed kyma module

---

.github/scripts/release.sh
.github/workflows/create-release.yaml

- Use the release id from the previous step

Simplify release id for assets

---

.github/workflows/markdown.yaml

- Fix link checker version
- https://github.com/kyma-project/serverless/pull/1207

Fix link checker version

---

tests/btp/hack/Makefile
tests/btp/hack/registry-availibility-check.sh

Fix retrying for req avail checks

---

components/operator/Dockerfile

Bump base go image

---

components/operator/api/v1alpha1/dockerregistry_types.go
components/operator/internal/chart/flags.go
components/operator/internal/state/installed_status.go
components/operator/internal/state/installed_status_test.go
components/operator/internal/state/storage.go
components/operator/internal/state/storage_test.go
config/docker-registry/README.md
config/docker-registry/values.yaml
config/operator/base/crd/bases/operator.kyma-project.io_dockerregistries.yaml
docs/user/resources/06-20-docker-registry-cr.md
go.mod

- add `.spec.storage.deleteEnabled` option
- https://github.com/kyma-project/docker-registry/issues/263

Allow users to delete images

---

components/operator/internal/chart/flags.go
components/operator/internal/state/storage_test.go

- https://github.com/kyma-project/docker-registry/issues/263

Restart registry deploy on its configmap content change

---

docs/user/_sidebar.md
docs/user/tutorials/01-10-use-registry-internally.md
docs/user/tutorials/01-30-remove-image-manifest.md

- make a tutorial that shows how to use the `deleteEnabled` field
- fix kyma cli usage in another tutorial
- https://github.com/kyma-project/docker-registry/issues/270

Document the `.spec.deleteEnabled` field

---

docs/user/00-30-storage-configuration.md

Add a note about the consequences of registry reconfiguration

---

config/operator/base/ui-extensions/dockerregistry/details
config/operator/base/ui-extensions/dockerregistry/form
config/operator/base/ui-extensions/dockerregistry/translations

- add status info to widget on details view in kyma dashboard
#263

Add storage info to status widget in UI

---

config/operator/base/kustomization.yaml

- change value of the `kyma-project.io/module` from the `dockerregistry-operator` to the `docker-registry`
- https://github.com/kyma-project/docker-registry/issues/282

Fix module label 

---

.github/scripts/upgrade-chart-version.sh
.github/workflows/create-release.yaml
components/operator/internal/chart/flags.go
components/operator/internal/chart/flags_test.go
components/operator/internal/state/access_test.go
components/operator/internal/state/apply.go
components/operator/internal/state/apply_test.go
components/operator/internal/state/state_test.go
components/operator/internal/state/storage_test.go
config/docker-registry/templates/_helpers.tpl
config/docker-registry/templates/configmap.yaml
config/docker-registry/templates/deployment.yaml
config/docker-registry/templates/ingress.yaml
config/docker-registry/templates/poddisruptionbudget.yaml
config/docker-registry/templates/priorityclass.yaml
config/docker-registry/templates/pvc.yaml
config/docker-registry/templates/registry-config.yaml
config/docker-registry/templates/secret.yaml
config/docker-registry/templates/service.yaml
config/docker-registry/templates/virtualservice.yaml
config/docker-registry/values.yaml

- set common labels for all chart resources
- upgrade module version and managed-by labels and commit them on release branch
- https://github.com/kyma-project/docker-registry/issues/282

Chart common labels

---

config/docker-registry/values.yaml

- format the `valyes.yaml` file using `yq` to not edit it every time on release like it is [here](https://github.com/kyma-project/docker-registry/commit/fd86073ca0c7af3cfd0e73f66aeac619855aa36f#diff-0932b01c78186ebdc482b37b38e3c136b4361b45cd075a1f0a236fb2daf27801)
**Related Issue(s):**
- https://github.com/kyma-project/docker-registry/issues/282

Format the values.yaml file

---

config/docker-registry/templates/deployment.yaml

- propagate commonLabels to the registry templates
- https://github.com/kyma-project/docker-registry/issues/282

Add commonLabels to templates

---

config/operator/base/deployment/deployment.yaml
config/operator/base/kustomization.yaml
config/operator/base/priority-class/kustomization.yaml
config/operator/base/priority-class/priority_class.yaml

Configure priorityClass for operator

---

config/operator/base/deployment/deployment.yaml
config/operator/base/kustomization.yaml
config/operator/base/priority-class/kustomization.yaml
config/operator/base/priority-class/priority_class.yaml

- cherry-pick https://github.com/kyma-project/docker-registry/pull/293

Cherry-Pick: Configure priorityClass for operator

---

.github/workflows/push.yaml

fix build job permissions

---

config/operator/base/cli-extensions/dockerregistry/kustomization.yaml
config/operator/base/cli-extensions/dockerregistry/rootCommand

- add api version
- improve long description
- https://github.com/kyma-project/serverless/issues/1520

Improve cli extension

---

docs/user/tutorials/01-20-expose-registry.md

- Remove unnecessary step
- Add "" to avoid problems

Fix expose registry tutorial

---

config/operator/base/cli-extensions/dockerregistry/actionCommands
config/operator/base/cli-extensions/dockerregistry/kustomization.yaml

- https://github.com/kyma-project/cli/issues/2425

Migrate coreCommands to actionCommands

---

config/operator/base/cli-extensions/dockerregistry/actionCommands
config/operator/base/cli-extensions/dockerregistry/kustomization.yaml

- cherry-pick: https://github.com/kyma-project/docker-registry/commit/0c963ca451c999df4415cbac35283c544f8910c6
- https://github.com/kyma-project/cli/issues/2428

Cherry-pick: Migrate coreCommands to actionCommands (#321)

---

config/docker-registry/files/kyma-commands.yaml
config/docker-registry/templates/cli-extension.yaml
config/operator/base/cli-extensions/dockerregistry/kustomization.yaml

-implement cli extensions with new api
- https://github.com/kyma-project/cli/issues/2428

New cli extensions configmap

---

docs/contributor/03-10-scripts-not-working.md

Replace Remedy with Solution

---

.github/scripts/upgrade-sec-scanners-config.sh
sec-scanners-config.yaml

- react to changes in the yq [v4.45.2](https://github.com/mikefarah/yq/releases/tag/v4.45.2) (Fixing add when there is no node match https://github.com/mikefarah/yq/issues/2325) and change images order

Fix the `sec-scanners-config.yaml` updater

---

docs/user/tutorials/01-10-use-registry-internally.md
docs/user/tutorials/01-30-remove-image-manifest.md
tests/btp/Makefile

- get rid of the `alpha` group when using the `registry` extension command
- https://github.com/kyma-project/cli/issues/2482

Migrate the `kyma registry` extension

---

.github/workflows/_build.yaml
components/operator/Dockerfile
components/registry-init/Dockerfile

- make sure all layers containing the go build command has the `--platform=$BUILDPLATFORM` flag and `GOOS=$TARGETOS GOARCH=$TARGETARCH` envs
- https://github.com/kyma-project/docker-registry/issues/366

Build multi-arch images

---

config/docker-registry/README.md
config/docker-registry/templates/deployment.yaml
config/docker-registry/templates/secret.yaml
config/docker-registry/values.yaml
sec-scanners-config.yaml

- Bump distribution to 3.0.0
- #353

Bump distribution to 3.0.0

---

.github/workflows/create-release.yaml

- upload file based on its ID
- print generated moduletemplate
- improve curl response handling
- https://github.com/kyma-project/docker-registry/issues/369#issue-3195596849

Upload community-module-template to the right release

---

module-config-template.yaml

- Change the module template link to the HP one

Change module template link

---

.github/workflows/publish-new-version.yaml

Rename promotion workflow

---

docs/user/tutorials/01-10-use-registry-internally.md
docs/user/tutorials/01-20-expose-registry.md
docs/user/tutorials/01-30-remove-image-manifest.md
tests/btp/Makefile

- update docs
- update tests
https://github.com/kyma-project/cli/releases/tag/3.1.0

Migrate tests and docs to cli v3.1
